services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m
      timeout: 30s
      start_period: 10s
    
  app: 
    build:
      context: .
      args:
        - DEV:true
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    
    command: > 
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"