services:
  db:
    image: postgres:14-alpine
    container_name: django-rest-pg
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1m
      timeout: 30s
      start_period: 10s

  app:
    build:
      context: .
      args:
        - DEV:true
    container_name: django-rest-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DEBUG=1
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    depends_on:
      db:
        condition: service_healthy

    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  dev-static-data:
